"""initial_schema

Revision ID: e88ade33dcb7
Revises: 
Create Date: 2026-09-22 21:04:36.104911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e88ade33dcb7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('city', sa.String(length=64), nullable=False),
    sa.Column('split_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('bccs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('zone', sa.String(length=128), nullable=False),
    sa.Column('crc_id', sa.Integer(), nullable=False),
    sa.Column('vhf_canal', sa.String(length=32), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['crc_id'], ['crcs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('feeders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bcc_id', sa.Integer(), nullable=False),
    sa.Column('ref', sa.String(length=16), nullable=False),
    sa.Column('nom', sa.String(length=128), nullable=False),
    sa.Column('poste_source', sa.String(length=64), nullable=False),
    sa.Column('zone', sa.String(length=64), nullable=False),
    sa.Column('mw_nominal', sa.Float(), nullable=False),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', 'P4', 'P5', name='feeder_priority'), nullable=False),
    sa.Column('statut', sa.Enum('Actif', 'Inactif', 'En maintenance', name='feeder_statut'), nullable=False),
    sa.ForeignKeyConstraint(['bcc_id'], ['bccs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('DN', 'CRC', 'BCC', name='user_role'), nullable=False),
    sa.Column('zone', sa.String(length=32), nullable=True),
    sa.Column('bcc_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bcc_id'], ['bccs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_ref', sa.String(length=64), nullable=False),
    sa.Column('order_type', sa.Enum('urgence', 'realim', name='order_type'), nullable=False),
    sa.Column('sub_type', sa.String(length=16), nullable=True),
    sa.Column('mw_total', sa.Float(), nullable=False),
    sa.Column('mw_nord', sa.Float(), nullable=False),
    sa.Column('mw_sud', sa.Float(), nullable=False),
    sa.Column('issued_by', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('target_crc_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'acknowledged', 'executing', 'completed', 'cancelled', name='order_status'), nullable=False),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_crc_id'], ['crcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_order_ref'), 'orders', ['order_ref'], unique=True)
    op.create_table('programmes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_date', sa.Date(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('draft', 'validated', 'active', 'completed', name='programme_status'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programmes_programme_date'), 'programmes', ['programme_date'], unique=True)
    op.create_table('executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feeder_id', sa.Integer(), nullable=False),
    sa.Column('bcc_id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_min', sa.Float(), nullable=True),
    sa.Column('mw_shed', sa.Float(), nullable=False),
    sa.Column('ens_mwh', sa.Float(), nullable=True),
    sa.Column('trigger', sa.Enum('j1', 'urgence', 'manual', name='execution_trigger'), nullable=False),
    sa.Column('status', sa.Enum('executing', 'restored', 'cancelled', name='execution_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bcc_id'], ['bccs.id'], ),
    sa.ForeignKeyConstraint(['feeder_id'], ['feeders.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_acks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bcc_id', sa.Integer(), nullable=True),
    sa.Column('mw_assigned', sa.Float(), nullable=False),
    sa.Column('mw_executed', sa.Float(), nullable=False),
    sa.Column('acked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'acknowledged', 'executing', 'completed', 'cancelled', name='ack_status'), nullable=False),
    sa.ForeignKeyConstraint(['bcc_id'], ['bccs.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('programme_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('programme_id', sa.Integer(), nullable=False),
    sa.Column('time_slot', sa.String(length=8), nullable=False),
    sa.Column('mw_national', sa.Float(), nullable=False),
    sa.Column('mw_nord', sa.Float(), nullable=False),
    sa.Column('mw_sud', sa.Float(), nullable=False),
    sa.Column('bcc_id', sa.Integer(), nullable=True),
    sa.Column('mw_bcc', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'assigned', 'validated', name='slot_status'), nullable=False),
    sa.ForeignKeyConstraint(['bcc_id'], ['bccs.id'], ),
    sa.ForeignKeyConstraint(['programme_id'], ['programmes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programme_slots')
    op.drop_table('order_acks')
    op.drop_table('executions')
    op.drop_index(op.f('ix_programmes_programme_date'), table_name='programmes')
    op.drop_table('programmes')
    op.drop_index(op.f('ix_orders_order_ref'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('feeders')
    op.drop_table('bccs')
    op.drop_table('crcs')
    # ### end Alembic commands ###
